### ISSUE TITLE
why is there a bug ?

### ISSUE THREAD

**Issue by paulorec** [victorlaerte/victorlaerte.github.io#3]
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BM5A8XF2AT18AHTWC3SW4848/The%20dog%20ate%20my%20commit)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BM5A8XF2AT18AHTWC3SW4848/The%20dog%20ate%20my%20commit/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BM5A8XF2AT18AHTWC3SW4848/That%27s%20a%20jerror)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BM5A8XF2AT18AHTWC3SW4848/That%27s%20a%20jerror/vote)

**Comment by interaminense** [comment]
🐶🐶🐶🐶
